### ISSUE TITLE
2021 dataset fails preprocessing on 2023_dev

### ISSUE THREAD

**Issue by initze** [awi-response/macs_processing#44]
```
(MACS37) D:\Pix4D_Processing\macs_processing_2023>python 01_SetupData.py -s WA_CapeBlossom_20210625_7cm_01.py
2024-02-16 14:38:35,106 Creation of logfile
2024-02-16 14:38:35,106 Settings File: WA_CapeBlossom_20210625_7cm_01.py
2024-02-16 14:38:35,309 Creating footprints selection
Checking Projects:
N:\Response\Restricted_Airborne\MACS\Canada\2018_MOSES
N:\Response\Restricted_Airborne\MACS\Alaska\2019_ThawTrend-Air
N:\Response\Restricted_Airborne\MACS\Alaska\2021_Perma-X_Alaska
Looking     center    left   right  total_images                                    Dataset
dataset_id
3           1853.0  1839.0  1828.0        5520.0     20210625-234543_51_BP_CapeBlossom_500m
6            892.0   882.0   747.0        2521.0    20210626-014401_52_BP_CapeBlossom_1500m
19            37.0    29.0    29.0          95.0                            20210627-204006
32           219.0   217.0     NaN         436.0       20210628-011258_07_CapeBlossom_1000m
33          1029.0   898.0   911.0        2838.0       20210628-013740_07_CapeBlossom_1000m
39            76.0    52.0    38.0         166.0    20210628-230058_17_BP_DrainedLake_1000m
68            62.0    39.0    50.0         151.0     20210703-225103_63_BP_ThawSlumps_1500m
69             1.0     NaN     NaN           1.0  20210703-235351_28_NOAT_NoatakDelta_1500m
71            47.0    40.0    40.0         127.0    20210710-000408_29_KOB_KobukDelta_1500m
79            62.0    47.0    50.0         159.0     20210710-054752_63_BP_ThawSlumps_1500m
Please select IDs (comma separated): 3
N:\Response\Restricted_Airborne\MACS\Canada\2023_Perma-X_Canada
Traceback (most recent call last):
  File "C:\Users\initze\.conda\envs\MACS37\lib\site-packages\pandas\core\indexes\base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2131, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2140, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 3

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Pix4D_Processing\macs_processing_2023\processing_utils.py", line 202, in get_dataset_name
    dataset_name = ds.loc[int(dataset_id)][name_attribute]
  File "C:\Users\initze\.conda\envs\MACS37\lib\site-packages\pandas\core\indexing.py", line 967, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\Users\initze\.conda\envs\MACS37\lib\site-packages\pandas\core\indexing.py", line 1202, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "C:\Users\initze\.conda\envs\MACS37\lib\site-packages\pandas\core\indexing.py", line 1153, in _get_label
    return self.obj.xs(label, axis=axis)
  File "C:\Users\initze\.conda\envs\MACS37\lib\site-packages\pandas\core\generic.py", line 3876, in xs
    loc = index.get_loc(key)
  File "C:\Users\initze\.conda\envs\MACS37\lib\site-packages\pandas\core\indexes\base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\initze\.conda\envs\MACS37\lib\site-packages\pandas\core\indexes\base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 144, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index_class_helper.pxi", line 41, in pandas._libs.index.Int64Engine._check_type
KeyError: '3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "01_SetupData.py", line 360, in <module>
    main()
  File "01_SetupData.py", line 100, in main
    dataset_name = get_dataset_name(ds, dataset_id)
  File "D:\Pix4D_Processing\macs_processing_2023\processing_utils.py", line 204, in get_dataset_name
    dataset_name = ds.loc[dataset_id][name_attribute]
  File "C:\Users\initze\.conda\envs\MACS37\lib\site-packages\pandas\core\indexing.py", line 967, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\Users\initze\.conda\envs\MACS37\lib\site-packages\pandas\core\indexing.py", line 1202, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "C:\Users\initze\.conda\envs\MACS37\lib\site-packages\pandas\core\indexing.py", line 1153, in _get_label
    return self.obj.xs(label, axis=axis)
  File "C:\Users\initze\.conda\envs\MACS37\lib\site-packages\pandas\core\generic.py", line 3876, in xs
    loc = index.get_loc(key)
  File "C:\Users\initze\.conda\envs\MACS37\lib\site-packages\pandas\core\indexes\base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: '3'
```

**Comment by initze** [comment]
done
